//
//  Card-Info.swift
//  Trusted-Tarot
//
//  Created by Lindsay Clifford on 5/11/24.
//

import Foundation

import Foundation

let cardInfoDictionary: [String: CardInfo] = [
    "The Fool": CardInfo(name: "The Fool", description: "The Fool represents new beginnings, spontaneity, and taking a leap of faith. It suggests that you should trust your instincts and follow your heart, even if it means taking a risk.", imageName: "O The Fool"),
    "The Magician": CardInfo(name: "The Magician", description: "The Magician represents manifesting your desires, creativity, and making things happen. It suggests that you have the power and resources to bring your ideas to life, and that you should use your skills and talents to create your own reality.", imageName: "1 The Magician"),
    "The High Priestess": CardInfo(name: "The High Priestess", description: "The High Priestess represents intuition, inner knowledge, and mystery. It suggests that you should trust your instincts and listen to your inner voice, as it will guide you to the answers you seek.", imageName: "2 The High Priestess"),
    "The Empress": CardInfo(name: "The Empress", description: "The Empress represents nurturing, abundance, and fertility. It suggests that you should nurture yourself and others, and that you should be open to receiving the abundance that the universe has to offer.", imageName: "3 The Empress"),
    "The Emperor": CardInfo(name: "The Emperor", description: "The Emperor represents authority, stability, and structure. It suggests that you should take charge of your life, establish clear boundaries, and create a solid foundation for yourself.", imageName: "4 The Emperor"),
    "The Hierophant": CardInfo(name: "The Hierophant", description: "The Hierophant represents tradition, conformity, and education. It suggests that you should seek guidance from a trusted mentor or teacher, and that you should follow the rules and norms of society.", imageName: "5 The Hierophant"),
    "The Lovers": CardInfo(name: "The Lovers", description: " The Lovers represent love, harmony, and partnership. It suggests that you should follow your heart and make choices based on love and compassion, and that you should strive to create harmonious relationships with others.", imageName: "6 The Lovers"),
    "The Chariot": CardInfo(name: "The Chariot", description: "The Chariot represents determination, willpower, and victory. It suggests that you should stay focused and determined, and that you will overcome obstacles and achieve your goals.", imageName: "7 The Chariot"),
    "Strength": CardInfo(name: "Strength", description: "Strength represents courage, patience, and inner strength. It suggests that you should face challenges with courage and patience, and that you have the inner strength to overcome any obstacle.", imageName: "8 Strength"),
    "The Hermit": CardInfo(name: "The Hermit", description: "The Hermit represents introspection, solitude, and self-discovery. It suggests that you should take time for yourself, reflect on your life, and seek the answers within.", imageName: "9 The Hermit"),
    "Wheel of Fortune": CardInfo(name: "Wheel of Fortune", description: "The Wheel of Fortune represents change, cycles, and fate. It suggests that life is always changing and that you should go with the flow and trust that everything happens for a reason.", imageName: "10 Wheel of Fortune"),
    "Justice": CardInfo(name: "Justice", description: "Justice represents fairness, balance, and accountability. It suggests that you should act with integrity and fairness, and that you will be held accountable for your actions.", imageName: "11 Justice"),
    "The Hanged Man": CardInfo(name: "The Hanged Man", description: " The Hanged Man represents surrender, letting go, and seeing things from a different perspective. It suggests that you should let go of what is no longer serving you and look at your life from a new angle.", imageName: "12 The Hanged Man"),
    "Death": CardInfo(name: "Death", description: "Death represents transformation, change, and rebirth. It suggests that you are undergoing a major transformation and that you should embrace the changes and let go of what is no longer serving you.", imageName: "13 Death"),
    "Temperance": CardInfo(name: "Temperance", description: " Temperance represents balance, moderation, and patience. It suggests that you should strive for balance in all areas of your life, and that you should be patient and moderate in your actions.", imageName: "14 Temperance"),
    "The Devil": CardInfo(name: "The Devil", description: "The Devil represents materialism, temptation, and bondage. It suggests that you should be aware of your desires and attachments, and that you should break free from any negative patterns or addictions.", imageName: "15 The Devil"),
    "The Tower": CardInfo(name: "The Tower", description: "The Tower represents sudden change, upheaval, and chaos. It suggests that you may be experiencing a major shake-up in your life, and that you should stay strong and adapt to the changes.", imageName: "16 The Tower"),
    "The Star": CardInfo(name: "The Star", description: "The Star represents hope, healing, and inspiration. It suggests that you should have faith in the future, and that you are being guided and supported by the universe.", imageName: "17 The Star"),
    "The Moon": CardInfo(name: "The Moon", description: " The Moon represents illusion, intuition, and the subconscious. It suggests that things may not be as they seem, and that you should trust your intuition and pay attention to your dreams and emotions.", imageName: "18 The Moon"),
    "The Sun": CardInfo(name: "The Sun", description: " The Sun represents joy, success, and vitality. It suggests that you are in a period of happiness and growth, and that you should celebrate your successes and enjoy life.", imageName: "19 The Sun"),
    "Judgement": CardInfo(name: "Judgement", description: " Judgment represents renewal, inner calling, and absolution. It suggests that you are undergoing a period of self-evaluation and reflection, and that you should listen to your inner calling and make positive changes in your life.", imageName: "20 Judgement"),
    "The World": CardInfo(name: "The World", description: "The World represents completion, fulfillment, and celebration. It suggests that you have reached the end of a cycle and that you should celebrate your achievements and enjoy the sense of completion and fulfillment.", imageName: "21 The World"),
    
    "Ace of Wands": CardInfo(name: "Ace of Wands", description: "The Ace of Wands represents new beginnings, inspiration, and creative energy. It suggests that you are being presented with a new opportunity or idea that has the potential to ignite your passion and enthusiasm.", imageName: "22 Ace of Wands"),
    "Two of Wands": CardInfo(name: "Two of Wands", description: "The Two of Wands represents planning, decision-making, and future vision. It suggests that you are at a crossroads and that you need to make a choice or decision about your future path.", imageName: "23 Two of Wands"),
    "Three of Wands": CardInfo(name: "Three of Wands", description: "The Three of Wands represents progress, expansion, and foresight. It suggests that your plans are starting to take shape and that you are making progress towards your goals.", imageName: "24 Three of Wands"),
    "Four of Wands": CardInfo(name: "Four of Wands", description: "The Four of Wands represents celebration, harmony, and completion. It suggests that you have reached a milestone or achieved a goal, and that it is time to celebrate and enjoy your success.", imageName: "25 Four of Wands"),
    "Five of Wands": CardInfo(name: "Five of Wands", description: "The Five of Wands represents conflict, competition, and struggle. It suggests that you may be facing challenges or obstacles, and that you need to assert yourself and stand up for what you believe in.", imageName: "26 Five of Wands"),
    "Six of Wands": CardInfo(name: "Six of Wands", description: "The Six of Wands represents victory, success, and recognition. It suggests that you have overcome challenges and achieved your goals, and that you are being celebrated and recognized for your achievements.", imageName: "27 Six of Wands"),
    "Seven of Wands": CardInfo(name: "Seven of Wands", description: "The Seven of Wands represents courage, determination, and defending your position. It suggests that you are facing challenges or opposition, and that you need to stand your ground and fight for what you believe in.", imageName: "28 Seven of Wands"),
    "Eight of Wands": CardInfo(name: "Eight of Wands", description: "The Eight of Wands represents movement, speed, and action. It suggests that things are moving quickly and that you need to stay focused and keep up with the pace.", imageName: "29 Eight of Wands"),
    "Nine of Wands": CardInfo(name: "Nine of Wands", description: "The Nine of Wands represents resilience, persistence, and determination. It suggests that you have been through challenges and setbacks, but that you are not giving up and are determined to keep going.", imageName: "30 Nine of Wands"),
    "Ten of Wands": CardInfo(name: "Ten of Wands", description: " The Ten of Wands represents burden, responsibility, and overload. It suggests that you are feeling weighed down by responsibilities or obligations, and that you need to prioritize and lighten your load.", imageName: "31 Ten of Wands"),
    "Page of Wands": CardInfo(name: "Page of Wands", description: "The Page of Wands represents enthusiasm, exploration, and inspiration. It suggests that you are eager to explore new ideas and possibilities, and that you are inspired and passionate about your pursuits.", imageName: "32 Page of Wands"),
    "Knight of Wands": CardInfo(name: "Knight of Wands", description: "The Knight of Wands represents energy, passion, and impulsiveness. It suggests that you are full of energy and enthusiasm, and that you are ready to take action and pursue your goals with passion and excitement.", imageName: "33 Knight of Wands"),
    "Queen of Wands": CardInfo(name: "Queen of Wands", description: "The Queen of Wands represents confidence, charisma, and independence. It suggests that you are a natural leader and that you have the confidence and charisma to inspire and motivate others.", imageName: "34 Queen of Wands"),
    "King of Wands": CardInfo(name: "King of Wands", description: "The King of Wands represents leadership, vision, and determination. It suggests that you have a clear vision of what you want to achieve, and that you are determined and driven to make your vision a reality.", imageName: "35 King of Wands"),
    
    "Ace of Cups": CardInfo(name: "Ace of Cups", description: "The Ace of Cups represents new emotions, love, and compassion. It suggests that you are being presented with a new opportunity for emotional growth and connection, and that you should embrace and nurture these emotions.", imageName: "36 Ace of Cups"),
    "Two of Cups": CardInfo(name: "Two of Cups", description: " The Two of Cups represents partnership, love, and harmony. It suggests that you are experiencing a deep emotional connection with someone, and that this relationship is based on mutual love and respect.", imageName: "37 Two of Cups"),
    "Three of Cups": CardInfo(name: "Three of Cups", description: " The Three of Cups represents celebration, friendship, and joy. It suggests that you are in a period of happiness and celebration, and that you should enjoy and appreciate the company of friends and loved ones.", imageName: "38 Three of Cups"),
    "Four of Cups": CardInfo(name: "Four of Cups", description: "The Four of Cups represents contemplation, apathy, and discontent. It suggests that you are feeling dissatisfied or bored with your current situation, and that you need to reflect on what you truly want and need.", imageName: "39 Four of Cups"),
    "Five of Cups": CardInfo(name: "Five of Cups", description: "The Five of Cups represents loss, grief, and disappointment. It suggests that you are experiencing feelings of sadness and regret, and that you need to acknowledge and process these emotions in order to heal.", imageName: "40 Five of Cups"),
    "Six of Cups": CardInfo(name: "Six of Cups", description: " The Six of Cups represents nostalgia, childhood memories, and innocence. It suggests that you are feeling sentimental and nostalgic, and that you may be reminiscing about the past or reconnecting with people from your childhood.", imageName: "41 Six of Cups"),
    "Seven of Cups": CardInfo(name: "Seven of Cups", description: "DThe Seven of Cups represents choices, illusions, and fantasies. It suggests that you are faced with multiple options and that you need to be careful not to get lost in illusions or fantasies, and to make choices based on reality.", imageName: "42 Seven of Cups"),
    "Eight of Cups": CardInfo(name: "Eight of Cups", description: "The Eight of Cups represents abandonment, walking away, and disillusionment. It suggests that you are feeling dissatisfied with your current situation and that you are ready to leave behind what is no longer serving you.", imageName: "43 Eight of Cups"),
    "Nine of Cups": CardInfo(name: "Nine of Cups", description: "The Nine of Cups represents contentment, satisfaction, and emotional fulfillment. It suggests that you are in a period of happiness and fulfillment, and that you should enjoy and appreciate the abundance and blessings in your life.", imageName: "44 Nine of Cups"),
    "Ten of Cups": CardInfo(name: "Ten of Cups", description: "The Ten of Cups represents joy, harmony, and family. It suggests that you are experiencing a sense of joy and fulfillment in your relationships, and that you are surrounded by love and support.", imageName: "45 Ten of Cups"),
    "Page of Cups": CardInfo(name: "Page of Cups", description: " The Page of Cups represents emotional curiosity, creativity, and intuition. It suggests that you are exploring your emotions and creativity, and that you are open to new ideas and possibilities.", imageName: "46 Page of Cups"),
    "Knight of Cups": CardInfo(name: "Knight of Cups", description: "The Knight of Cups represents romanticism, idealism, and pursuit of emotions. It suggests that you are following your heart and pursuing your desires, and that you are open to new emotional experiences and relationships.", imageName: "47 Knight of Cups"),
    "Queen of Cups": CardInfo(name: "Queen of Cups", description: "The Queen of Cups represents empathy, intuition, and emotional depth. It suggests that you are a compassionate and intuitive person, and that you are in tune with your emotions and the emotions of others.", imageName: "48 Queen of Cups"),
    "King of Cups": CardInfo(name: "King of Cups", description: "The King of Cups represents emotional maturity, diplomacy, and calmness. It suggests that you are emotionally balanced and mature, and that you are able to navigate emotional situations with calmness and diplomacy.", imageName: "49 King of Cups"),
        
    
    "Ace of Swords": CardInfo(name: "Ace of Swords", description: " The Ace of Swords represents clarity, breakthrough, and intellectual power. It suggests that you are gaining a new understanding or insight, and that you should use your intellect and mental clarity to make decisions and solve problems.", imageName: "50 Ace of Swords"),
    "Two of Swords": CardInfo(name: "Two of Swords", description: "The Two of Swords represents indecision, blocked emotions, and avoiding the truth. It suggests that you are facing a difficult decision or situation, and that you need to confront your emotions and face the truth in order to move forward.", imageName: "51 Two of Swords"),
    "Three of Swords": CardInfo(name: "Three of Swords", description: "The Three of Swords represents heartbreak, grief, and separation. It suggests that you are experiencing emotional pain and loss, and that you need to allow yourself to grieve and heal.", imageName: "52 Three of Swords"),
    "Four of Swords": CardInfo(name: "Four of Swords", description: "The Four of Swords represents rest, relaxation, and recuperation. It suggests that you need to take a break and allow yourself time to rest and recharge, both mentally and physically.", imageName: "53 Four of Swords"),
    "Five of Swords": CardInfo(name: "Five of Swords", description: "The Five of Swords represents conflict, betrayal, and competition. It suggests that you may be involved in a situation involving conflict or rivalry, and that you need to be careful not to engage in dishonest or manipulative behavior.", imageName: "54 Five of Swords"),
    "Six of Swords": CardInfo(name: "Six of Swords", description: "The Six of Swords represents transition, change, and moving forward. It suggests that you are moving away from a difficult situation and towards a more positive and stable future.", imageName: "55 Six of Swords"),
    "Seven of Swords": CardInfo(name: "Seven of Swords", description: "The Seven of Swords represents deception, strategy, and sneakiness. It suggests that you may need to be strategic or use your wits to navigate a difficult situation, but that you should be careful not to resort to dishonesty or deceit.", imageName: "56 Seven of Swords"),
    "Eight of Swords": CardInfo(name: "Eight of Swords", description: "The Eight of Swords represents restriction, entrapment, and fear. It suggests that you are feeling trapped or restricted in some way, and that you need to confront your fears and limitations in order to break free.", imageName: "57 Eight of Swords"),
    "Nine of Swords": CardInfo(name: "Nine of Swords", description: "The Nine of Swords represents anxiety, worry, and insomnia. It suggests that you are experiencing stress and worry, and that you need to find ways to manage and cope with these negative thoughts and emotions.", imageName: "58 Nine of Swords"),
    "Ten of Swords": CardInfo(name: "Ten of Swords", description: "The Ten of Swords represents betrayal, defeat, and endings. It suggests that you are experiencing a difficult ending or setback, and that you need to accept and learn from the situation in order to move forward.", imageName: "59 Ten of Swords"),
    "Page of Swords": CardInfo(name: "Page of Swords", description: "The Page of Swords represents curiosity, intellectual energy, and new ideas. It suggests that you are eager to learn and explore new ideas, and that you should stay curious and open-minded.", imageName: "60 Page of Swords"),
    "Knight of Swords": CardInfo(name: "Knight of Swords", description: "The Knight of Swords represents ambition, assertiveness, and action. It suggests that you are ready to take action and pursue your goals with determination and focus.", imageName: "61 Knight of Swords"),
    "Queen of Swords": CardInfo(name: "Queen of Swords", description: " The Queen of Swords represents independence, clarity, and direct communication. It suggests that you are a clear thinker and communicator, and that you value honesty and integrity in your interactions with others.", imageName: "62 Queen of Swords"),
    "King of Swords": CardInfo(name: "King of Swords", description: "The King of Swords represents authority, intellectual power, and objective decision-making. It suggests that you are a fair and rational leader, and that you should use your intellect and objectivity to make wise decisions and solve problems.", imageName: "63 King of Swords"),
    
    "Ace of Pentacles": CardInfo(name: "Ace of Pentacles", description: "The Ace of Pentacles represents new financial opportunities, prosperity, and abundance. It suggests that you are being presented with a new opportunity for financial growth and stability, and that you should seize this opportunity and invest in your future.", imageName: "64 Ace of Pentacles"),
    "Two of Pentacles": CardInfo(name: "Two of Pentacles", description: "The Two of Pentacles represents balance, adaptability, and juggling priorities. It suggests that you are faced with multiple responsibilities or demands, and that you need to stay flexible and adaptable in order to manage your priorities.", imageName: "65 Two of Pentacles"),
    "Three of Pentacles": CardInfo(name: "Three of Pentacles", description: "The Three of Pentacles represents teamwork, collaboration, and craftsmanship. It suggests that you are working with others to achieve a common goal, and that your skills and expertise are being recognized and valued.", imageName: "66 Three of Pentacles"),
    "Four of Pentacles": CardInfo(name: "Four of Pentacles", description: "The Four of Pentacles represents security, stability, and possessiveness. It suggests that you are focused on maintaining financial security and stability, but that you should be careful not to become too possessive or attached to material possessions.", imageName: "67 Four of Pentacles"),
    "Five of Pentacles": CardInfo(name: "Five of Pentacles", description: "The Five of Pentacles represents financial hardship, insecurity, and isolation. It suggests that you may be experiencing financial difficulties or feeling isolated or unsupported, and that you need to seek help and support from others.", imageName: "68 Five of Pentacles"),
    "Six of Pentacles": CardInfo(name: "Six of Pentacles", description: " The Six of Pentacles represents generosity, charity, and sharing. It suggests that you are in a position to give to others, and that you should be generous and compassionate in your interactions with others.", imageName: "69 Six of Pentacles"),
    "Seven of Pentacles": CardInfo(name: "Seven of Pentacles", description: "The Seven of Pentacles represents patience, perseverance, and long-term planning. It suggests that you are working towards a long-term goal, and that you need to be patient and persistent in order to achieve your objectives.", imageName: "70 Seven of Pentacles"),
    "Eight of Pentacles": CardInfo(name: "Eight of Pentacles", description: "The Eight of Pentacles represents skill development, dedication, and hard work. It suggests that you are focused on honing your skills and putting in the effort required to achieve your goals.", imageName: "71 Eight of Pentacles"),
    "Nine of Pentacles": CardInfo(name: "Nine of Pentacles", description: " The Nine of Pentacles represents financial independence, self-sufficiency, and abundance. It suggests that you are in a period of financial stability and that you are able to enjoy the fruits of your labor.", imageName: "72 Nine of Pentacles"),
    "Ten of Pentacles": CardInfo(name: "Ten of Pentacles", description: "The Ten of Pentacles represents financial success, family, and legacy. It suggests that you are experiencing financial prosperity and that you are focused on creating a legacy for yourself and your family.", imageName: "73 Ten of Pentacles"),
    "Page of Pentacles": CardInfo(name: "Page of Pentacles", description: "The Page of Pentacles represents financial opportunity, practicality, and diligence. It suggests that you are eager to explore new financial opportunities and that you should approach these opportunities with diligence and practicality.", imageName: "74 Page of Pentacles"),
    "Knight of Pentacles": CardInfo(name: "Knight of Pentacles", description: "The Knight of Pentacles represents reliability, responsibility, and hard work. It suggests that you are a dependable and hardworking individual, and that you are focused on achieving your financial goals through steady and consistent effort.", imageName: "75 Knight of Pentacles"),
    "Queen of Pentacles": CardInfo(name: "Queen of Pentacles", description: "The Queen of Pentacles represents nurturing, practicality, and financial stability. It suggests that you are a compassionate and nurturing individual, and that you are focused on creating a stable and secure environment for yourself and your loved ones.", imageName: "76 Queen of Pentacles"),
    "King of Pentacles": CardInfo(name: "King of Pentacles", description: "The King of Pentacles represents financial success, stability, and leadership. It suggests that you are a successful and stable individual, and that you are able to provide financial security and leadership for yourself and others.", imageName: "77 King of Pentacles")

]
